# Generated by Django 3.2.16 on 2025-11-26 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('category', models.CharField(blank=True, choices=[('no', 'Без категории'), ('2', 'Вторая категория'), ('1', 'Первая категория'), ('top', 'Высшая категория')], max_length=50, null=True, verbose_name='Квалификационная категория')),
                ('snils', models.CharField(max_length=11, unique=True, verbose_name='СНИЛС')),
                ('medical_license_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер медицинской лицензии')),
                ('medical_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Медицинская организация')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография / О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
    ]
