# Generated by Django 3.2.16 on 2025-11-27 05:22

from django.db import migrations, models
import user_settings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[user_settings.validators.check_string_only], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, validators=[user_settings.validators.check_string_only], verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, help_text='Необязательное поле', max_length=40, validators=[user_settings.validators.check_string_only], verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=14, unique=True, validators=[user_settings.validators.check_snils], verbose_name='СНИЛС')),
                ('phone', models.CharField(blank=True, max_length=20, unique=True, validators=[user_settings.validators.check_phone], verbose_name='Телефон')),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[user_settings.validators.real_age], verbose_name='Дата рождения')),
            ],
        ),
    ]
