# Generated by Django 3.2.16 on 2025-11-26 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_number', models.CharField(max_length=20, unique=True, verbose_name='Номер медицинской карты')),
                ('oms_number', models.CharField(help_text='16 цифр нового образца', max_length=16, unique=True, verbose_name='Номер полиса ОМС')),
                ('snils', models.CharField(help_text='Формат: XXX-XXX-XXX XX', max_length=14, unique=True, verbose_name='СНИЛС')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='ФИО контактного лица')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Телефон контактного лица')),
                ('blood_type', models.CharField(blank=True, choices=[('0+', '0 (I) Rh+'), ('0-', '0 (I) Rh-'), ('A+', 'A (II) Rh+'), ('A-', 'A (II) Rh-'), ('B+', 'B (III) Rh+'), ('B-', 'B (III) Rh-'), ('AB+', 'AB (IV) Rh+'), ('AB-', 'AB (IV) Rh-')], max_length=3, null=True, verbose_name='Группа крови')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Аллергии')),
                ('chronic_conditions', models.TextField(blank=True, null=True, verbose_name='Хронические заболевания')),
                ('disability_group', models.CharField(blank=True, choices=[('I', 'I группа'), ('II', 'II группа'), ('III', 'III группа'), ('Нет', 'Нет инвалидности')], max_length=5, null=True, verbose_name='Группа инвалидности')),
                ('primary_physician', models.CharField(blank=True, max_length=100, null=True, verbose_name='Участковый врач')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-date_created'],
            },
        ),
    ]
