# Generated by Django 3.2.16 on 2025-11-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='snils',
        ),
    ]
