# Generated by Django 3.2.16 on 2025-11-27 09:47

from django.db import migrations, models
import django.db.models.deletion
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_snils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_record_number',
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('0+', '0 (I) Rh+'), ('0-', '0 (I) Rh-'), ('A+', 'A (II) Rh+'), ('A-', 'A (II) Rh-'), ('B+', 'B (III) Rh+'), ('B-', 'B (III) Rh-'), ('AB+', 'AB (IV) Rh+'), ('AB-', 'AB (IV) Rh-')], help_text='Необязательное поле', max_length=3, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability_group',
            field=models.CharField(blank=True, choices=[('I', 'I группа'), ('II', 'II группа'), ('III', 'III группа'), ('Нет', 'Нет инвалидности')], help_text='Необязательное поле', max_length=5, null=True, verbose_name='Группа инвалидности'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=100, null=True, validators=[patients.validators.check_string_only], verbose_name='ФИО контактного лица для экстренной связи'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=20, null=True, validators=[patients.validators.check_phone], verbose_name='Телефон контактного лица для экстренной связи'),
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер медицинской карты')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
                'ordering': ['-date_created'],
            },
        ),
    ]
