# Generated by Django 3.2.16 on 2025-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20251127_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='number',
            field=models.IntegerField(max_length=20, unique=True, verbose_name='Номер медицинской карты'),
        ),
    ]
