# Generated by Django 3.2.16 on 2025-11-27 10:35

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_medicalcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='number',
            field=models.CharField(help_text='Уникальный номер медицинской карты пациента в поликлинике', max_length=20, unique=True, validators=[patients.validators.check_string_only], verbose_name='Номер медицинской карты'),
        ),
    ]
