# Generated by Django 3.2.16 on 2025-11-27 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_medicalcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='number',
            field=models.BigIntegerField(help_text='Уникальный номер медицинской карты пациента', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999)], verbose_name='Номер медицинской карты'),
        ),
    ]
