# Generated by Django 3.2.16 on 2025-11-28 11:39

from django.db import migrations, models
import django.db.models.deletion
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_medicalcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='number',
            field=models.CharField(help_text='Уникальный номер медицинской карты пациента', max_length=20, unique=True, verbose_name='Номер медицинской карты'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oms_number',
            field=models.CharField(help_text='16 цифр нового образца', max_length=16, unique=True, validators=[patients.validators.digits_only], verbose_name='Номер полиса ОМС'),
        ),
    ]
